CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar NOT NULL,
  "password" varchar NOT NULL,
  "age" int NOT NULL,
  "created_at" timestamp DEFAULT 'Now()'
);

CREATE TABLE "courses" (
  "couse_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text NOT NULL,
  "user_id" int NOT NULL,
  "level_id" int NOT NULL,
  "category_id" int NOT NULL,
  "teacher" varchar NOT NULL,
  "created_at" timestamp DEFAULT 'Now()'
);

CREATE TABLE "course_levels" (
  "level_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "course_videos" (
  "video_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text NOT NULL,
  "course_id" int NOT NULL,
  "url" text NOT NULL,
  "created_at" timestamp DEFAULT 'Now()'
);

CREATE TABLE "categories" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" text NOT NULL
);

ALTER TABLE "courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "course_levels" ("level_id");

ALTER TABLE "course_videos" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("couse_id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id");
